### ISSUE TITLE
Working with npm and gulp and gulp tasks

### ISSUE THREAD

**Issue by 0dp** [Thomas-A-Reinert/Understrap-Documentation#2]
Do we need both?

Thomas, you and someone else spoke about a VS code specific setup for gulp in a thread. Maybe we should include that in the gulp topic if it's worth it?  I don't use vs code myself so it's your call

**Comment by Thomas-A-Reinert** [comment]
Ah no. I meant a setup for VSC like .editorconfig for any other editor. VSC uses it´s own config. Didn´t have anything to do with Gulp.

**Comment by Thomas-A-Reinert** [comment]
Anyway, I also updated the vscode specific settings in my latest commit..
